class NotFoundError(Exception):
    pass


class AlreadyExistError(Exception):
    pass
